# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IRkwu\Documents\Codigos\Codigos_Python\Equipo3-Farmacia\Uis\VentanaIngresarCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from Clases.Cliente import Cliente

class VentanaIngresarCliente(object):
    def setupUi(self, VentanaIngresarCliente):
        ImagenBanner = QtGui.QPixmap('Imagenes/banner_cvi.png')
        
        
        VentanaIngresarCliente.setEnabled(True)
        VentanaIngresarCliente.resize(800, 565)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        
        VentanaIngresarCliente.setSizePolicy(sizePolicy)
        VentanaIngresarCliente.setMinimumSize(QtCore.QSize(800, 565))
        VentanaIngresarCliente.setMaximumSize(QtCore.QSize(800, 565))
        
        # Etiqueta nombres y LineEdit
        self.nombresLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.nombresLabel.setGeometry(QtCore.QRect(9, 137, 42, 50))
        self.nombresLineEdit = QtWidgets.QLineEdit(VentanaIngresarCliente)
        self.nombresLineEdit.setGeometry(QtCore.QRect(106, 137, 260, 50))
        
        # Etiqueta apellidos y LineEdit
        self.apellidosLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.apellidosLabel.setGeometry(QtCore.QRect(399, 137, 42, 50))
        self.apellidosLineEdit = QtWidgets.QLineEdit(VentanaIngresarCliente)
        self.apellidosLineEdit.setGeometry(QtCore.QRect(504, 137, 260, 50))
        
        # Etiqueta genero y ComboBox
        self.generoLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.generoLabel.setGeometry(QtCore.QRect(9, 229, 35, 50))
        self.generoComboBox = QtWidgets.QComboBox(VentanaIngresarCliente)
        self.generoComboBox.setGeometry(QtCore.QRect(106, 229, 260, 50))
        self.generoComboBox.setMinimumSize(QtCore.QSize(260, 50))
        self.generoComboBox.setEditable(False)
        self.generoComboBox.addItem("")
        self.generoComboBox.addItem("")
        
        # Etiqueta fecha_nacimiento y DateEdit
        self.fecha_nacimientoLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.fecha_nacimientoLabel.setGeometry(QtCore.QRect(399, 229, 99, 50))
        self.fecha_nacimientoDateEdit = QtWidgets.QDateEdit(VentanaIngresarCliente)
        self.fecha_nacimientoDateEdit.setGeometry(QtCore.QRect(504, 229, 260, 50))
        
        # Etiqueta rut y LineEdit
        self.rutLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.rutLabel.setGeometry(QtCore.QRect(9, 321, 17, 50))
        self.rutLineEdit = QtWidgets.QLineEdit(VentanaIngresarCliente)
        self.rutLineEdit.setGeometry(QtCore.QRect(106, 321, 260, 50))
    
        # Etiqueta telefono y LineEdit
        self.telefonoLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.telefonoLabel.setGeometry(QtCore.QRect(399, 321, 42, 50))
        self.telefonoLineEdit = QtWidgets.QLineEdit(VentanaIngresarCliente)
        self.telefonoLineEdit.setGeometry(QtCore.QRect(504, 321, 260, 50))
        self.telefonoLineEdit.setValidator(QIntValidator())
        self.telefonoLineEdit.setMaxLength(9)
        
        # Etiqueta email y LineEdit
        self.emailLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.emailLabel.setGeometry(QtCore.QRect(9, 413, 24, 50))
        self.emailLineEdit = QtWidgets.QLineEdit(VentanaIngresarCliente)
        self.emailLineEdit.setGeometry(QtCore.QRect(106, 413, 260, 50))
        
        # Etiqueta domicilio y LineEdit
        self.domicilioLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.domicilioLabel.setGeometry(QtCore.QRect(399, 413, 40, 50))
        self.domicilioLineEdit = QtWidgets.QLineEdit(VentanaIngresarCliente)
        self.domicilioLineEdit.setGeometry(QtCore.QRect(504, 413, 260, 50))        
        
        # Btoton ingresar y accion al pulsar
        self.btnIngresar = QtWidgets.QPushButton(VentanaIngresarCliente)
        self.btnIngresar.setGeometry(QtCore.QRect(9, 505, 85, 50))
        self.btnIngresar.clicked.connect(self.onActionBtnIngresar)
        
        # Etiqueta regresar y accion al pulsar
        self.btnRegresar = QtWidgets.QPushButton(VentanaIngresarCliente)
        self.btnRegresar.setGeometry(QtCore.QRect(20, 20, 80, 50))
        self.btnRegresar.setStyleSheet("background-color: transparent;\n""border: none;\n""")
        self.btnRegresar.clicked.connect(VentanaIngresarCliente.close)
        
        # Etiqueta estatus cliente
        self.estatusLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.estatusLabel.setGeometry(QtCore.QRect(106, 505, 685, 51))
        
        # Etiqueta imagen superior
        self.imagen_on_topLabel = QtWidgets.QLabel(VentanaIngresarCliente)
        self.imagen_on_topLabel.setGeometry(QtCore.QRect(0, 0, 801, 91))
        self.imagen_on_topLabel.setText("")
        self.imagen_on_topLabel.setPixmap(ImagenBanner)
        
        # Definir textos
        self.retranslateUi(VentanaIngresarCliente)

        # Conectar todo
        QtCore.QMetaObject.connectSlotsByName(VentanaIngresarCliente)

    # Metodo definir textos
    def retranslateUi(self, VentanaIngresarCliente):
        _translate = QtCore.QCoreApplication.translate
        VentanaIngresarCliente.setWindowTitle(_translate("VentanaIngresarCliente", "Ventana - Ingresar Cliente"))
        self.nombresLabel.setText(_translate("VentanaIngresarCliente", "Nombres"))
        self.apellidosLabel.setText(_translate("VentanaIngresarCliente", "Apellidos"))
        self.generoLabel.setText(_translate("VentanaIngresarCliente", "Genero"))
        self.generoComboBox.setItemText(0, _translate("VentanaIngresarCliente", "Masculino"))
        self.generoComboBox.setItemText(1, _translate("VentanaIngresarCliente", "Femenino"))
        self.fecha_nacimientoLabel.setText(_translate("VentanaIngresarCliente", "Fecha de Nacimiento"))
        self.rutLabel.setText(_translate("VentanaIngresarCliente", "Rut"))
        self.telefonoLabel.setText(_translate("VentanaIngresarCliente", "Telefono"))
        self.emailLabel.setText(_translate("VentanaIngresarCliente", "Email"))
        self.domicilioLabel.setText(_translate("VentanaIngresarCliente", "Domicilio"))
        self.btnIngresar.setText(_translate("VentanaIngresarCliente", "Ingresar Cliente"))

    # Accion al clickear boton ingresar
    def onActionBtnIngresar(self):
        nombres = self.nombresLineEdit.text()
        apellidos = self.apellidosLineEdit.text()
        genero = self.generoComboBox.currentText()
        fecha_nacimiento = self.fecha_nacimientoDateEdit.date().toString("dd/MM/yyyy")
        rut = self.rutLineEdit.text()
        telefono =self.telefonoLineEdit.text()
        email = self.emailLineEdit.text()
        domicilio = self.domicilioLineEdit.text()
                
        Cliente.agregar_cliente(nombres, apellidos, domicilio, genero, fecha_nacimiento, rut, email, telefono)
        self.estatusLabel.setText("El usuario: "+nombres+" "+apellidos+" ha sido ingresado")
        
        # Limpiar LineEdit
        self.nombresLineEdit.setText("")
        self.apellidosLineEdit.setText("")
        self.fecha_nacimientoDateEdit.setDate(QtCore.QDate.fromString("01/01/2000", "dd/MM/yyyy"))
        self.rutLineEdit.setText("")
        self.emailLineEdit.setText("")
        self.telefonoLineEdit.setText("")
        


